// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWTMqmv_gi4dmZ_aEnlTTm7Z9sq9T6scA',
    appId: '1:151980946245:web:e772299a4a0bbfa72dc42c',
    messagingSenderId: '151980946245',
    projectId: 'projectsamaya-73382',
    authDomain: 'projectsamaya-73382.firebaseapp.com',
    storageBucket: 'projectsamaya-73382.appspot.com',
    measurementId: 'G-YSY6TH0CVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgCCNY9_Whp4rLXaQsxEYZDq7zurT9sFI',
    appId: '1:151980946245:android:57a756db7dab79062dc42c',
    messagingSenderId: '151980946245',
    projectId: 'projectsamaya-73382',
    storageBucket: 'projectsamaya-73382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoqjA2kWKXRupHHUvGMJBFKgygJ8yd8hE',
    appId: '1:151980946245:ios:196864e0ec7f07362dc42c',
    messagingSenderId: '151980946245',
    projectId: 'projectsamaya-73382',
    storageBucket: 'projectsamaya-73382.appspot.com',
    iosBundleId: 'com.example.projectSamaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoqjA2kWKXRupHHUvGMJBFKgygJ8yd8hE',
    appId: '1:151980946245:ios:affcb44d713d9b882dc42c',
    messagingSenderId: '151980946245',
    projectId: 'projectsamaya-73382',
    storageBucket: 'projectsamaya-73382.appspot.com',
    iosBundleId: 'com.example.projectSamaya.RunnerTests',
  );
}
